[[rocm_cmake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "566b28f4b92ca79fa8e76d4a5e8335082bd111af"
libc = "glibc"
os = "linux"

    [[rocm_cmake.download]]
    sha256 = "4d69e34971283e2c66ba8a4c0cb53a59fc967db486a107fbe7511b2fdd13d956"
    url = "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.4.4+0/rocm_cmake.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[rocm_cmake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "566b28f4b92ca79fa8e76d4a5e8335082bd111af"
libc = "musl"
os = "linux"

    [[rocm_cmake.download]]
    sha256 = "4d69e34971283e2c66ba8a4c0cb53a59fc967db486a107fbe7511b2fdd13d956"
    url = "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v5.4.4+0/rocm_cmake.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
