[[rocm_cmake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ab30198787bb338cacd00a10db6eefe12889cfc"
libc = "glibc"
os = "linux"

    [[rocm_cmake.download]]
    sha256 = "3324eac103057b62024ed9d515fcf496b6ae5454643b828803e622676a11a1ea"
    url = "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v6.0.0+0/rocm_cmake.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rocm_cmake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ab30198787bb338cacd00a10db6eefe12889cfc"
libc = "musl"
os = "linux"

    [[rocm_cmake.download]]
    sha256 = "3324eac103057b62024ed9d515fcf496b6ae5454643b828803e622676a11a1ea"
    url = "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v6.0.0+0/rocm_cmake.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
