[[rocm_cmake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9203efda939f47b3c60ef808a37a8eb9d6e33d5a"
libc = "glibc"
os = "linux"

    [[rocm_cmake.download]]
    sha256 = "96eb66f3ca13694a3f8d731a801957fe0b53725fec2f693408bf51043bd8ad83"
    url = "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.2.0+0/rocm_cmake.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rocm_cmake]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db9333def1f2ba529d4c9c47ca4f0e2a48ed4dc4"
libc = "musl"
os = "linux"

    [[rocm_cmake.download]]
    sha256 = "51d03d821797a0596093ae7d70a843fa50b099a6ea1c0b2895613d7666ccee60"
    url = "https://github.com/JuliaBinaryWrappers/rocm_cmake_jll.jl/releases/download/rocm_cmake-v4.2.0+0/rocm_cmake.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
